import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/sidebar";
import Layout from "./components/layout";

const robotoRegular = localFont({
  src: "./fonts/Roboto-Regular.ttf",
  variable: "--font-roboto-regular",
  weight: "400",
});
const robotoBold = localFont({
  src: "./fonts/Roboto-Bold.ttf",
  variable: "--font-roboto-bold",
  weight: "700",
});
const robotoMedium = localFont({
  src: "./fonts/Roboto-Medium.ttf",
  variable: "--font-roboto-medium",
  weight: "500",
});

export const metadata = {
  title: "Sistema de cadastro - APAE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={`${robotoRegular.variable} ${robotoMedium.variable} ${robotoBold.variable} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
